CREATE DATABASE IF NOT EXISTS organization;
USE organization;


CREATE TABLE organization_register (
org_id INT AUTO_INCREMENT PRIMARY KEY,
org_name VARCHAR(100) NOT NULL,
org_email VARCHAR(100) NOT NULL UNIQUE,
org_password VARCHAR(255) NOT NULL,
mobile_number VARCHAR(20) NOT NULL UNIQUE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE employees (
emp_id INT AUTO_INCREMENT PRIMARY KEY,
org_id INT NOT NULL,
empname VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
dob DATE NOT NULL,
mobile VARCHAR(20) NOT NULL UNIQUE,
category VARCHAR(50) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (org_id) REFERENCES organization_register(org_id) ON DELETE CASCADE
);


CREATE TABLE employees_master (
id INT AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(100) NOT NULL UNIQUE,
mobile VARCHAR(20) NOT NULL UNIQUE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE attendance (
id INT AUTO_INCREMENT PRIMARY KEY,
emp_id INT NOT NULL,
org_id INT NOT NULL,
date DATE NOT NULL,
status ENUM('present','absent','late') DEFAULT 'present',
time_in TIME DEFAULT NULL,
time_out TIME DEFAULT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UNIQUE KEY unique_attendance (emp_id,date),
FOREIGN KEY (emp_id) REFERENCES employees(emp_id) ON DELETE CASCADE,
FOREIGN KEY (org_id) REFERENCES organization_register(org_id) ON DELETE CASCADE
);


CREATE TABLE contact_messages (
id INT AUTO_INCREMENT PRIMARY KEY,
org_id INT NOT NULL,
name VARCHAR(100) NOT NULL,
email VARCHAR(150) NOT NULL,
subject VARCHAR(200) NOT NULL,
message TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (org_id) REFERENCES organization_register(org_id) ON DELETE CASCADE
);
